-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "auto",
})

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@144",
	position = "auto",
	scale = 1.2,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080@120",
	position = "auto",
	scale = 1,
})

hl.workspace_rule({
	workspace = "name:shell",
	monitor = "eDP-1",
	default = true,
})

hl.workspace_rule({
	workspace = "name:web",
	monitor = "HDMI-A-1",
	on_created_empty = "brave",
})

hl.workspace_rule({
	workspace = "special:notes",
	on_created_empty = "obsidian",
})

hl.workspace_rule({
	workspace = "special:music",
	on_created_empty = "pear-desktop",
})

hl.workspace_rule({
	workspace = "special:exposed",
	gaps_out = 60,
	gaps_in = 30,
	border_size = 5,
})

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

local terminal = "foot"

local browser = "brave"

local editor = "nvim"

local fileManager = "yazi"

local menu = "fuzzel"

local layout = "master"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_THEME", "catppuccin-mocha-sky-cursors")

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_THEME", "catppuccin-mocha-sky-cursors")

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("HYPR_DEFAULT_LAYOUT", "master")

hl.env("GTK_THEME", "Viola-Dark-GTK")

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

hl.env("QT_IM_MODULE", "fcitx")

hl.env("XMODIFIERS", "@im=fcitx")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("SWWW_TRANSITION_FPS", 60)

hl.env("SWWW_TRANSITION", "any")

hl.env("SWWW_TRANSITION_DURATION", 4)

hl.env("EDITOR", "nvim")

hl.env("WALLPAPERS", "/home/daviddeadly/dotfiles/images/wallpapers")

hl.env("SSH_AUTH_SOCK", os.getenv("XDG_RUNTIME_DIR") .. "/ssh-agent.socket")

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 10,
		gaps_out = 30,
		border_size = 3,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "master",
		col = {
			active_border = { colors = { "rgb(94e2d5)", "rgb(24273A)", "rgb(24273A)", "rgb(94e2d5)" }, angle = 45 },
			inactive_border = { colors = { "rgb(24273A)", "rgb(24273A)", "rgb(24273A)", "rgb(24273A)" }, angle = 45 },
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 10,
		rounding_power = 2,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.8,
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = "rgba(cba6f7ee)",
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 3,
			passes = 1,
			contrast = 1.3,
			vibrancy = 0.1696,
			brightness = 1,
			xray = true,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
	animations = {
		enabled = true,
		-- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
})

-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrule = bordersize 0, floating:0, onworkspace:f[1]

-- windowrule = rounding 0, floating:0, onworkspace:f[1]

--##############

--## WINDOWS ###

--##############

hl.window_rule({
	name = "terminal opaque",
	match = {
		initial_title = "^(" .. terminal .. ")$",
	},
	opacity = "0.8 0.7",
})

hl.window_rule({
	name = "small floating volume manager",
	match = {
		class = "^(.*pavucontrol.*)$",
	},
	float = true,
	dim_around = true,
	move = { "(cursor_x-(window_w*0.5))", "(cursor_y+(window_h*0.05))" },
})

hl.window_rule({
	name = "clean browser",
	match = {
		class = "^(" .. browser .. "-browser)$",
	},
	workspace = "name:web",
	opacity = "0.9 0.8",
})

hl.window_rule({
	name = "floating devops",
	match = {
		class = "^(" .. browser .. "-browser)$",
		initial_title = "^(DevTools)$",
		title = "^(DevTools)(.*)$",
	},
	float = true,
	no_blur = true,
	no_shadow = true,
	size = { "monitor_w*0.4", "monitor_h*0.5" },
	move = { "(cursor_x-(window_w*0.5))", "(cursor_y-(window_h*0.5))" },
})

hl.window_rule({
	name = "obsidian on notes workspace",
	match = {
		initial_title = "^(.*Obsidian.*)$",
	},
	workspace = "special:notes",
	no_blur = true,
})

hl.window_rule({
	name = "youtube music on music workspace",
	match = {
		class = "(.*youtube_music)$",
	},
	workspace = "special:music",
})

hl.window_rule({
	name = "floating clipboard manager",
	match = {
		class = "(.*copyq.*)",
	},
	float = true,
	dim_around = true,
	size = { "monitor_w*0.3", "monitor_h*0.4" },
	move = { "(cursor_x-(window_w*0.5))", "(cursor_y-(window_h*0.5))" },
})

-- patches

hl.window_rule({
	name = "Ignore maximize requests from apps",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

hl.window_rule({
	name = "dragging issues with xwayland",
	match = {
		class = "^$",
		title = "^$",
		xwayland = 1,
		float = 1,
		fullscreen = 0,
		pin = 0,
	},
	no_focus = true,
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		preserve_split = true,
		-- Preserve splits when toggling between layouts
		force_split = 2,
		--always split to the right (new = right or bottom)
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		new_status = "slave",
		new_on_active = "after",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = -1,
		disable_hyprland_logo = false,
		-- If true disables the random hyprland logo / anime girl background. :(
		on_focus_under_fullscreen = true,
		mouse_move_enables_dpms = true,
		key_press_enables_dpms = true,
		initial_workspace_tracking = true,
	},
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "latam",
		kb_options = "caps:ctrl_modifier",
		follow_mouse = 1,
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = true,
		},
		tablet = {
			relative_input = true,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

-- device { }

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd(terminal .. "client"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.exec_cmd(terminal))

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd(browser))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "X", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "X", hl.dsp.exit())

hl.bind("CTRL" .. " + " .. "code:20", hl.dsp.exec_cmd("wtype -M ctrl \\' -m ctrl"))

-- Utilities

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd(terminal .. "client yazi"))

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd("fuzzel"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "SPACE", hl.dsp.exec_cmd("~/.config/hypr/scripts/fuzzel-calculator.sh"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("copyq toggle"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("BEMOJI_PICKER_CMD='fuzzel --dmenu' bemoji"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("hyprpicker| wl-copy"))

hl.bind(mainMod .. " + " .. "code:47", hl.dsp.exec_cmd("wlogout -b 5 -c 0 -r 0 --protocol layer-shell"))

hl.bind(
	mainMod .. " + " .. "ALT" .. " + " .. "SPACE",
	hl.dsp.exec_cmd("awww img $(~/.config/hypr/scripts/select_wallpaper.sh)")
)

hl.bind(mainMod .. " + " .. "Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh"))

hl.bind(mainMod .. " + " .. "G", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle_layout.sh"))

hl.bind("Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh true"))

-- web apps

hl.bind(mainMod .. " + " .. "Y", hl.dsp.exec_cmd('brave --app="https://youtube.com"'))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("pypr wall next"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("pypr wall clear"))

hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("pypr zoom ++0.5"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Z", hl.dsp.exec_cmd("pypr zoom"))

hl.bind(mainMod .. " + " .. "T", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "O", hl.dsp.exec_cmd("hyprctl dispatch setprop active opaque toggle"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "S", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(mainMod .. " + " .. "R", hl.dsp.submap("Resize"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "down" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.move({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.move({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.move({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = "shell" }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = "web" }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = "name:shell" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = "name:web" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

-- Move window to workspace without switching

hl.bind(
	mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 1,
	hl.dsp.window.move({ workspace = "name:shell" }, { follow = false })
)

hl.bind(
	mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 2,
	hl.dsp.window.move({ workspace = "name:web" }, { follow = false })
)

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "up", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "K", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "J", hl.dsp.focus({ workspace = "e-1" }))

-- gestures

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

hl.gesture({ fingers = 3, direction = "down", mods = "SUPER", action = "close" })

-- special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "D", hl.dsp.workspace.toggle_special("notes"))

hl.bind(mainMod .. " + " .. "M", hl.dsp.workspace.toggle_special("music"))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

hl.bind(mainMod .. " + " .. "code:73", hl.dsp.exec_cmd("hyprctl hyprsunset temperature 2500"))

hl.bind(mainMod .. " + " .. "code:74", hl.dsp.exec_cmd("hyprctl hyprsunset temperature identity"))

-- Requires playerctl

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"))

hl.define_submap("Resize", function()
	-- Correct syntax: hl.dsp.window.resize({ x = val, y = val, relative = true })
	hl.bind("right", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })
	hl.bind("left", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })
	hl.bind("up", hl.dsp.window.resize({ x = 0, y = -20, relative = true }), { repeating = true })
	hl.bind("down", hl.dsp.window.resize({ x = 0, y = 20, relative = true }), { repeating = true })
	-- Vim style keys
	hl.bind("L", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })
	hl.bind("H", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })
	hl.bind("K", hl.dsp.window.resize({ x = 0, y = -20, relative = true }), { repeating = true })
	hl.bind("J", hl.dsp.window.resize({ x = 0, y = 20, relative = true }), { repeating = true })

	-- Reset submap
	hl.bind(mainMod .. "+R", hl.dsp.submap("reset"))
end)

-- disable_logs = false;

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("mako")
	hl.exec_cmd("pypr")
	hl.exec_cmd("ianny")
	hl.exec_cmd("waybar")
	hl.exec_cmd("fcitx5")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("localsend")
	hl.exec_cmd("otd-daemon")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("foot --server")
	hl.exec_cmd("copyq --start-server")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("~/.config/hypr/scripts/g-keyring.sh")
	hl.exec_cmd("~/.config/hypr/scripts/battery_check.sh")
	hl.exec_cmd("~/.config/hypr/scripts/toggle_layout.sh true")
	hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME")
	hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
end)
